### ISSUE TITLE
Newbie - error when building from source

### ISSUE THREAD

**Issue by andrew-codechimp** [lukakerr/twig#11]
I'm a complete newbie to xcode/swift so this is probably a stupid error but I'm interested in learning via this project.

I followed the instructions for building and using latest XCode Version 9.4.1 (9F2000) but getting an error within several Highlightr files.

> 'Key' is not a member type of 'NSAttributedString'

Be grateful for any guidance to why this is happening and how to fix.

**Comment by lukakerr** [comment]
Ah, that’s happening because the project is using Swift 4.2 which is currently in beta and requires Xcode 10. Ideally I’d like to support older versions of Swift too, so I’ll push a fix for this sometime today, thanks for reporting it!

**Comment by lukakerr** [comment]
This should be fixed in 4564ac1. If you still get the error, let me know
