### ISSUE TITLE
Misspelled words don't get red squiggly underlined

### ISSUE THREAD

**Issue by markmals** [lukakerr/twig#17]
When a word is misspelled, it is not underlined with a red squiggly line, though you are able to right click to correct it.

<img width="1249" alt="screen shot 2018-09-01 at 6 52 22 pm" src="https://user-images.githubusercontent.com/39869007/44951412-55660e80-ae18-11e8-98f3-5da11e92b6d3.png">
<img width="493" alt="screen shot 2018-09-01 at 6 52 25 pm" src="https://user-images.githubusercontent.com/39869007/44951411-55660e80-ae18-11e8-8b9f-9b93e2367dbc.png">

**Comment by lukakerr** [comment]
Should be fixed now
