### ISSUE TITLE
Color for a selected file

### ISSUE THREAD

**Issue by TofPlay** [lukakerr/twig#22]
![image](https://user-images.githubusercontent.com/1082222/46255884-2e483e80-c4a3-11e8-8e3c-b31fa4f58da8.png)
When we select a file we can hardly read his name

**Comment by Ethenyl** [comment]
Hi,

I'll be working on the issue and opening a PR soon ;-)

**Comment by lukakerr** [comment]
Awesome @Ethenyl ! For dark mode Twig actually already supports it, you just need to enable the system theme in preferences

**Comment by Ethenyl** [comment]
Hi @TofPlay,

Can you give me more information about your macOS settings :
- Appearance
- Accent colour
- Highlight colour

I've tried different settings and I can't reproduce the same effect as your screenshot.

**Comment by TofPlay** [comment]
@Ethenyl sure!
![image](https://user-images.githubusercontent.com/1082222/47105649-cb95c780-d244-11e8-8851-67f0b0c2cfe7.png)
I hope it's will help

**Comment by TofPlay** [comment]
I'm on macOS Hight Sierra 10.13.6
![](https://snag.gy/0dZjWp.jpg)

**Comment by lukakerr** [comment]
I believe this should be fixed in https://github.com/lukakerr/twig/commit/cfbfaab4f6b84a450df36709b4f90f5b5c7fc488#diff-7d7207b5d9425d357c97cb86046ef748R259.

If you still experience this problem after the next release, feel free to re-open this issue.
