### ISSUE TITLE
Nested numeric lists get flattened

### ISSUE THREAD

**Issue by jdickey** [lukakerr/twig#23]
Whether in the right-pane preview or exporting to either PDF or HTML, Twig can't tell that indenting some list items relative to others has significance.

Here's a selection of Markdown content that will demonstrate the problem:

```markdown
First, we'll build out the basic, as-generated Hanami app in a Docker image. Initially starting from a Debian base, we'll build an image that

1. installs the Debian packages we've been using for our Ruby-development images, including the requirements (Qt5's `qmake`, `xvfb`, etc) for an image hosting `capybara-webkit` and/or `selenium`;
2. installs the current versions of Gems for
  1. Hanami 1.2; and
  2. Our evolving-standard suite of development tools, including
    1. `awesome_print`,
    2. `flay`,
    3. `flog`,
    4. `reek`,
    5. `rubocop`,
    6. `pry-byebug`,
    7. `simplecov`,
    8. various MiniTest add-ons.
```

(GitHub's Markdown renderer sees that's a numbered list with three levels of indentation.

How Twig renders that content can be seen here:

<img width="1119" alt="capturfiles" src="https://user-images.githubusercontent.com/157938/46484354-34844500-c82c-11e8-86e3-599b0b90ea36.png">

Obviously not what the markup specifies.

(Possibly related to #18.)

**Comment by lukakerr** [comment]
It seems that GitHub uses a minimum of 3 (or 2?) spaces for nested indentation, whereas Twig (and cmark) use 4 spaces or a tab. In the screenshot below, using 4 spaces (or a tab) works fine. I don't intend to deviate from the cmark spec too much, so I'll close this as wontfix.

<img width="1381" alt="screen shot 2018-10-06 at 12 41 06 pm" src="https://user-images.githubusercontent.com/20056300/46566611-2be35a00-c965-11e8-8538-c291290192d5.png">
