### ISSUE TITLE
Install via home brew

### ISSUE THREAD

**Issue by universvm** [lukakerr/twig#28]
Hey there! The project is really cool! 

I'd love to be able to install (and update) through homebrew. Are you thinking about supporting it any time soon?

**Comment by lukakerr** [comment]
Thanks! I have opened a PR to add it to homebrew cask, it can be found here: https://github.com/Homebrew/homebrew-cask/pull/58815. When it is merged I will update the README with further installation instructions

**Comment by universvm** [comment]
Awesome, thank you!

**Comment by vitorgalvao** [comment]
Merged.
