### ISSUE TITLE
Cannot delete files/folders from sidebar once added

### ISSUE THREAD

**Issue by jpinnix** [lukakerr/twig#29]
If you open a folder or a file, they are added to the sidebar. However, there is no way to remove them.

<img width="208" alt="screen shot 2019-02-13 at 2 05 44 pm" src="https://user-images.githubusercontent.com/4436/52740557-dfee9480-2f98-11e9-911c-3bca1cd424f4.png">

**Comment by lukakerr** [comment]
The ability to remove top level folders and files from the sidebar was implemented in 3256737. It will be included in the next release.

**Comment by jpinnix** [comment]
Thanks, @lukakerr 👏
