### ISSUE TITLE
can you release a compiled app that can directly run under macOS

### ISSUE THREAD

**Issue by freesouls** [lukakerr/twig#3]
## Release A Compiled App

Hi, thanks for your excellent work!

Can you release a compiled app that can directly run under macOS(most famous repo will offer this kind of things), so users can just drag and drop the app in the Application Folder, compiling from the source is a little bit harder for normal user.

Thanks in advance!

**Comment by freesouls** [comment]
sorry, I see some info about releases in README.md.  Close this issue!

**Comment by lukakerr** [comment]
I've just released the first version of Twig - https://github.com/lukakerr/twig/releases/tag/0.0.1. There are likely to be bugs, so if you use it and encounter any bugs or have a feature request, please raise an issue
