### ISSUE TITLE
Crash after selecting several Preferences

### ISSUE THREAD

**Issue by gbkline** [lukakerr/twig#43]
1. Opened an .md file from a GitHub project
2. Opened Preferences
3. Changed Theme from ocean to pqraiso-dark
4. Clicked Use system appearance
5. Clicked Enable spellcheck

Relaunched and the spellcheck was still enabled.

Cannot reproduce.

[Twig_2019-03-04-153258_1501gtf1.crash.zip](https://github.com/lukakerr/twig/files/2928611/Twig_2019-03-04-153258_1501gtf1.crash.zip)

**Comment by lukakerr** [comment]
Thanks for reporting, I believe this should now be fixed in 9b74372. It seems that Highlightr's `setCodeFont` is not thread safe. If you experience the crash in the next release, feel free to re-open this issue
