### ISSUE TITLE
Question on features

### ISSUE THREAD

**Issue by BasThomas** [lukakerr/twig#5]
### I'm submitting a
- [ ] bug report
- [ ] feature request
- [x] question

### Other information

One of the unsupported features is what you call "Markdown shortcuts/auto pair". What exactly do you mean with that? If you're referring to what I think, which is to have shortcuts to make eg. some text bold or wrap it as a url, take a look at [the implementation from GitHawk](https://github.com/GitHawkApp/GitHawk/blob/5c15a3d61a98933f660704288c45e8759b77ba8e/Classes/Views/IssueTextActionsView%2BMarkdown.swift#L13-L76); that might be a good starting point.

**Comment by lukakerr** [comment]
Thats right, I was thinking of having keyboard shortcuts to insert markdown statements, e.g. `** **` for bold text, as well as when a user types the start of a statement the rest of it gets autocompleted and their cursor is positioned in the correct position ready to start typing.

I had a look at the GitHawk implementation, it looks awesome, thanks for recommending it. It seems like the main replacement is done [here in the replace() method](https://github.com/GitHawkApp/GitHawk/blob/d6197526345ffad30b6e00b147d21a160d906ac4/Classes/Views/UITextView%2BSelectedRange.swift#L47-L77)? I can probably work off of that to implement it

**Comment by BasThomas** [comment]
Looks like it, yes. cc @rnystrom. Maybe we can put this markdown logic in a library?
